<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success_page'] = array(
         'title' => 'Success',
         'page callback' => 'cipher_success',
         'access callback' => TRUE,
         'type' => MENU_CALLBACK,
     );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter a shift value.'),
    );

    $form['direction'] = array(
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction, i.e. right or left.'),
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter a phrase to encrypt.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'See Results',
    );

    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'cipher_success_page';
}

function cipher_success() {
    return 'Hello!';
}
